#!/bin/sh

BIN_DIR=./bin
SRC_DIR=.
CC=clang
CFLAGS="-nostdlib -ffreestanding -std=c89 -pedantic -Wall -Wextra -Werror -O3"
BUILD_OPTIONS="-static -fvisibility=hidden"
COMMAND="${CC} ${CFLAGS}  ${SRC_DIR}/compiler.c ${BUILD_OPTIONS} -o ${BIN_DIR}/famc"
echo ${COMMAND};
${COMMAND};

